# The Basics
# --------------------
title:          "IPDB"
description:    "The Interplanetary Database."
url:            "https://ipdb.io"

analyticsID:    "UA-60614729-9"
typekitID:      "bko7hwo"

signup:
    button: "Sign up for free (testnet)"
    button_short: "Sign up"
    link: "https://developers.ipdb.io/signup?plan_ids[]=2357355879577"

login:
    button: "Log in"
    link: "https://developers.ipdb.io/login"

# Form actions
forms:
    contact: '#'
    newsletter: "//foundation.us15.list-manage.com/subscribe/post?u=036bac2d4e3a3ea3de876a8dd&amp;id=8a21e3e9ca"

# Urls
# --------------------
permalink:      /:title/


# Generator
# --------------------
source:         ./_src
destination:    ./_dist


# Collections
# --------------------
collections:
    docs:
        output: true


# Plugins
# --------------------
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from

exclude:
    - "*README.md"
